mysqlconfig:
    host: 47.97.202.23
    port: 3306
    username: root
    passwd: root
    mysqlconnmaxidle: 20         #mysql连接池最大连接数量
    mysqlconnmaxopen: 10          #mysql连接池最大已连接的数量
















